apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-crru
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-crru@sha256:fb97bc11694a10a1465bb717c5651a3be7193bd4f66ffa6121a02ddea6acfeef
        name: my-nodejs
        resources: {}
status: {}
